### ISSUE TITLE
Improve diffed graph assembly UI/Colour

### ISSUE THREAD

**Issue by r0ny123** [HongThatCong/diaphora_py2#1]
After diffing, IDA displayed the diffed graph view with weird color (see below). Any possible fix for that?

![image](https://user-images.githubusercontent.com/49360849/88934039-c5e46700-d29d-11ea-850b-2d1c7d890bea.png)

**Comment by HongThatCong** [comment]
@r0ny123 
File diaphora.py, from line 850, function compare_graphs_pass, have some defined constant for color of graph.
You can choose another color follow your color favorites.
BR

**Comment by r0ny123** [comment]
Gotcha! Again thanks man for porting diaphora to older IDA.
